apiVersion: v1
kind: Service
metadata:
  name: sampleapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: sampleappport
      protocol: TCP
  selector:
    app: sampleapp
