# build.yml
on:
  pull_request:
    paths:
    - app/**
  push:
    paths:
    - app/**
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master

name: Build and Push to ACR

env:
  CONTAINER_IMAGE: sampleapp:${{ github.sha }}

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup ACR
      run: |
        # Login to Azure ACR
        docker login -u gousiya573 -p O9q4KE7pkjsajdaeL1P=fol7wOph4ZfX gousiya573.azurecr.io
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t $CONTAINER_IMAGE -t gousiya573.azurecr.io/$CONTAINER_IMAGE .
    # Only push to registry on master
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        # Push image to Azure ACR
        docker push gousiya573.azurecr.io/$CONTAINER_IMAGE
