# build.yml
on:
  pull_request:
    paths:
    - app.py
  push:
    paths:
    - app.py
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master

name: Build and Push to ACR

env:
  CONTAINER_IMAGE: pythonapp:${{ github.sha }}
  ACR_USERNAME: azacr
  ACR_PASSWORD: e=0Dcn8rrtbnc+3rmCuWd3W3VXVETH=0WyU
  ACR_LOGIN_SERVER: azacr.azurecr.io

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup ACR
      run: |
        # Login to Azure ACR
        docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_LOGIN_SERVER
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t $CONTAINER_IMAGE -t $ACR_LOGIN_SERVER/$CONTAINER_IMAGE .
    # Only push to registry on master
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        # Push image to Azure ACR
        docker push $ACR_LOGIN_SERVER/$CONTAINER_IMAGE
